TMP_FILE="/tmp/random_kanji.txt"

declare -A kanji
# From Heisig (250)
kanji["口"]="口:Mouth\nOn: コウ、ク\nKun: くち"
kanji["日"]="日:Day\nOn: ニチ、ジツ\nKun: ひ、か"
kanji["月"]="月:Month\nOn: ゲツ、ガツ\nKun: つき"
kanji["田"]="田:Rice field\nOn: デン、た\nKun: た"
kanji["目"]="目:Eye\nOn: モク、ボク\nKun: め、ま"
kanji["古"]="古:Old\nOn: コ、ふる\nKun: ふるい"
kanji["吾"]="吾:I, Myself\nOn: ゴ\nKun: われ、われ"
kanji["冒"]="冒:Risk\nOn: ボウ\nKun: おかす"
kanji["朋"]="朋:Companion\nOn: トウ\nKun: とも"
kanji["明"]="明:Bright\nOn: メイ、ミョウ\nKun: あかり、あかるい"
kanji["唱"]="唱:Chant\nOn: ショウ\nKun: となえる"
kanji["晶"]="晶:Sparkle\nOn: ショウ\nKun: あきらか"
kanji["品"]="品:Goods\nOn: ヒン、ホン\nKun: しな"
kanji["呂"]="呂:Spine\nOn: ロ\nKun: うなじ"
kanji["昌"]="昌:Prosperous\nOn: \nKun: さかん"
kanji["早"]="早:Early\nOn: ソウ、サッ\nKun: はやい、はやく"
kanji["旭"]="旭:Rising sun\nOn: キョク\nKun: あさひ"
kanji["世"]="世:Generation\nOn: セイ、 セ、 ソウ\nKun: よ"
kanji["胃"]="胃:Stomach\nOn: イ"
kanji["旦"]="旦:Nightbreak\nOn: タン、 ダン\nKun:  あき.らか、 あきら、 ただし、 あさ、 あした" 
kanji["胆"]="胆:Gall bladder\nOn: タン\nKun: きも"
kanji["亘"]="亘:Span\nOn: コウ、 カン、 セン\nKun: わた.る、 もと.める"
kanji["凹"]="凹:Concave\nOn: オウ\nKun: くぼ.む、 へこ.む、 ぼこ"
kanji["凸"]="凸:Convex\nOn: トツ\nKun: でこ"
kanji["旧"]="旧:Olden days\nOn: キュウ\nKun: ふる.い、 もと"
kanji["自"]="自:Oneself\nOn: ジ、 シ\nKun: みずか.ら、 おの.ずから、 おの.ずと"
kanji["白"]="白:White\nOn: ハク、 ビャク\nKun: しろ、 しら-、 しろ.い"
kanji["百"]="百:Hundred\nOn: ヒャク、 ビャク\nKun: もも"
kanji["中"]="中:In\nOn: チュウ\nKun: なか、 うち、 あた.る"
kanji["千"]="千:Thousand\nOn: セン\nKun: ち"
kanji["舌"]="舌:Tongue\nOn: ゼツ\nKun: した"
kanji["升"]="升:Measuring box\nOn: ショウ\nKun: ます"
kanji["昇"]="昇:Rise up\nOn: ショウ\nKun: のぼ.る"
kanji["丸"]="丸:Round\nOn: ガン\nKun:  まる、 まる.める、 まる.い"
kanji["寸"]="寸:Measurement\nOn: スン"
kanji["専"]="専:Specialty\nOn: セン\nKun: もっぱ.ら"
kanji["博"]="博:Dr.\nOn: ハク、 バク"
kanji["占"]="占:Fortune telling\nOn: セン\nKun: し.める、 うらな.う"
kanji["上"]="上:Above\nOn:  ジョウ、 ショウ、 シャン\nKun: うえ、 -うえ、 うわ-、 かみ、 あ.げる、 -あ.げる、 あ.がる、 -あ.がる、 あ.がり、 -あ.がり、 のぼ.る、 のぼ.り、 のぼ.せる、 のぼ.す、 たてまつ.る"
kanji["下"]="下:Below\nOn: カ、 ゲ\nKun: した、 しも、 もと、 さ.げる、 さ.がる、 くだ.る、 くだ.り、 くだ.す、 -くだ.す、 くだ.さる、 お.ろす、 お.りる"
kanji["卓"]="卓:Eminent\nOn: タク"
kanji["朝"]="朝:Morning\nOn: チョウ\nKun: あさ"
kanji["只"]="只:Only\nOn: シ\nKun: ただ"
kanji["貝"]="貝:Shellfish\nOn: バイ\nKun: かい"
kanji["貞"]="貞:Upright\nOn:  テイ、 ジョウ\nKun: ただし.い、 さだ"
kanji["員"]="員:Employee\nOn: イン"
kanji["見"]="見:See\nOn: ケン\nKun: み.る、 み.える、 み.せる"
kanji["児"]="児:Newborn babe\nOn: ジ、 ニ、 ゲイ\nKun: こ、 -こ、 -っこ"
kanji["元"]="元:Beginning\nOn: ゲン、 ガン\nKun: もと"
kanji["頁"]="頁:Page (*head)\nOn: ケツ\nKun: ぺえじ、 おおがい、 かしら"
kanji["頑"]="頑:Stubborn\nOn: ガン\nKun: かたく.な"
kanji["凡"]="凡:Mediocre\nOn: ボン、 ハン\nKun: およ.そ、 おうよ.そ、 すべ.て"
kanji["負"]="負:Defeat\nOn: フ\nKun: ま.ける、 ま.かす、 お.う"
kanji["万"]="万:Ten thousand\nOn: マン、 バン\nKun: よろず"
kanji["句"]="句:Phrase\nOn: ク"
kanji["肌"]="肌:Texture\nOn: キ\nKun: はだ"
kanji["旬"]="旬:Decameron\nOn: ジュン、 シュン"
kanji["勺"]="勺:Ladle\nOn:  シャク"
kanji["的"]="的:Bull's eye\nOn: テキ\nKun: まと"
kanji["首"]="首:Neck\nOn:  シュ\nKun: くび"
kanji["乙"]="乙:Fishguts\nOn: オツ、 イツ\nKun: おと-、 きのと"
kanji["乱"]="乱:Riot\nOn: ラン、 ロン\nKun: みだ.れる、 みだ.る、 みだ.す、 みだ、 おさ.める、 わた.る"
kanji["直"]="Straightaway\nOn: チョク、 ジキ、 ジカ\nKun: ただ.ちに、 なお.す、 -なお.す、 なお.る、 なお.き、 す.ぐ"
kanji["具"]="具:Tool\nOn:  グ\nKun: そな.える、 つぶさ.に"
kanji["真"]="真:True\nOn:  シン\nKun: ま、 ま-、 まこと"
kanji["工"]="工:Craft\nOn: コウ、 ク、 グ"
kanji["左"]="左:Left\nOn: サ、 シャ\nKun: ひだり"
kanji["右"]="右:Right\nOn: ウ、 ユウ\nKun: みぎ"
kanji["有"]="有:Possess\nOn: ユウ、 ウ\nKun: あ.る"
kanji["賄"]="賄:Bribe\nOn: ワイ\nKun:  まかな.う"
kanji["貢"]="貢:Tribute\nOn: コウ、 ク\nKun:  みつ.ぐ"
kanji["項"]="項:Paragraph\nOn: コウ\nKun: うなじ"
kanji["刀"]="刀:Sword\nOn: トウ\nKun: かたな、 そり"
kanji["刃"]="刃:Blade\nOn: ジン、 ニン\nKun:  は、 やいば、 き.る"
kanji["切"]="切:Cut\nOn: セツ、 サイ\nKun: き.る、 -き.る、 き.り、 -き.り、 -ぎ.り、 き.れる、 -き.れる、 き.れ、 -き.れ、 -ぎ.れ"
kanji["召"]="召:Seduce\nOn:  ショウ\nKun:  め.す"
kanji["昭"]="昭:Shining\nOn: ショウ"
kanji["則"]="則:Rule\nOn: ソク\nKun: のっと.る、 のり、 すなわち"
kanji["副"]="副:Vice\nOn: フク"
kanji["別"]="別:Separate\nOn: ベツ\nKun:  わか.れる、 わ.ける"
kanji["丁"]="丁:Street (+*nail or spike)\nOn:  チョウ、 テイ、 チン、 トウ、 チ\nKun:  ひのと"
kanji["町"]="町:Village\nOn:  チョウ\nKun: まち"
kanji["可"]="可:Can\nOn:  カ、 コク\nKun: べ.き、 -べ.し"
kanji["頂"]="頂:Place on the head\nOn: チョウ\nKun:  いただ.く、 いただき"
kanji["子"]="子:Child\nOn: シ、 ス、 ツ\nKun: こ、 -こ、 ね"
kanji["孔"]="孔:Cavity\nOn:  コウ、 ク\nKun: あな"
kanji["了"]="了:Complete\nOn: リョウ"
kanji["女"]="女:Woman\nOn: ジョ、 ニョ、 ニョウ\nKun: おんな、 め"
kanji["好"]="好:Fond\nOn: コウ\nKun: この.む、 す.く、 よ.い、 い.い"
kanji["如"]="如:Likeness\nOn:  ジョ、 ニョ\nKun:  ごと.し"
kanji["母"]="母:Mama / mother\nOn: ボ\nKun: はは、 も"
kanji["貫"]="貫:Pierce\nOn: カン\nKun: つらぬ.く、 ぬ.く、 ぬき"
kanji["兄"]="兄:Elder brother (*teenager)\nOn: ケイ、 キョウ\nKun:  あに"
kanji["克"]="克:Overcome\nOn: コク\nKun:  か.つ"
kanji["小"]="小:Little\nOn: ショウ\nKun: ちい.さい、 こ-、 お-、 さ-"
kanji["少"]="少:Few\nOn: ショウ\nKun: すく.ない、 すこ.し"
kanji["大"]="大:Large (St. Bernard dog)\nOn:  ダイ、 タイ\nKun: おお-、 おお.きい、 -おお.いに"
kanji["多"]="多:Many\nOn: タ\nKun: おお.い、 まさ.に、 まさ.る"
kanji["夕"]="夕:Evening\nOn: セキ\nKun: ゆう"
kanji["汐"]="汐:Eventide\nOn: セキ\nKun:  しお、 うしお、 せい"
kanji["外"]="外:Outside\nOn:  ガイ、 ゲ\nKun:  そと、 ほか、 はず.す、 はず.れる、 と-"
kanji["名"]="名:Name\nOn: メイ、 ミョウ\nKun: な、 -な"
kanji["石"]="石:Stone (*stone/rocks)\nOn: セキ、 シャク、 コク\nKun:  いし"
kanji["肖"]="肖:Resemblance (*spark or candle)\nOn: ショウ\nKun: あやか.る"
kanji["硝"]="硝:Nitrate\nOn:  ショウ"
kanji["砕"]="砕:Smash\nOn: サイ\nKun: くだ.く、 くだ.ける"
kanji["砂"]="砂:Sand\nOn:  サ、 シャ\nKun: すな"
kanji["削"]="削:Plane\nOn: サク\nKun: けず.る、 はつ.る、 そ.ぐ"
kanji["光"]="光:Ray\nOn: コウ\nKun:  ひか.る、 ひかり"
kanji["太"]="太:Plump\nOn: タイ、 タ\nKun:  ふと.い、 ふと.る"


# Pick a random kanji

keys=("${!kanji[@]}")
random_key="${keys[RANDOM % ${#keys[@]}]}"
random_val="${kanji[$random_key]}"


escaped_jp=$(echo "$random_key" | sed 's/"/\\"/g')
escaped_en=$(echo "$random_val" | sed 's/"/\\"/g')

# For opening link to dict
echo "$random_key" > "$TMP_FILE"

# Output clean JSON
printf '{"text":"%s","tooltip":"%s"}\n' "$escaped_jp" "$escaped_en"



